### ISSUE TITLE
Set how many times the keyword must exist on the page for an alert to be sent

### ISSUE THREAD

**Issue by ItIsSeven** [hmtessier/InStockNotifier#1]
Is it possible to create something in the `sites.json` file so I can set how many times a keyword must exist on a page for it to send an alert. I want to monitor a page for the words "Add to cart", but it already exists on the page, so I'd need to make it recognize how many times it exists on the page and send an alert when it goes above X amount. 
I thought this would be the most simplest way to implement something like this rather than going down the "looking at specific elements/sections of page route".

Thanks for your work on this project it's been very useful for me, hopefully I can get ahold of a CPU and GPU soon!

**Comment by hmtessier** [comment]
One option is to change the "alert" parameter to false and change the keyword to "Out of stock" (or whatever it says on the page. That way you won't receive an alert while it's out of stock but you will receive one once that out of stock disappears. This should get around the issue of multiple "add to cart"s on a single page.

**Comment by ItIsSeven** [comment]
I think you may have misunderstood what I meant.
On the page that I want to set an alert for there is multiple "Add to cart" buttons, lets say right now there's 3 "Add to cart" buttons (3 different products). I want to know when the number exceeds 3...
With how the script is programmed right now this isn't possible, since it will send an alert not based on how many times the text exists but based only if if the text exists.

**Comment by hmtessier** [comment]
No, I understood what you meant. At the moment there is no way to do that. The alternative i mentioned above though should be a workaround for your issue.

**Comment by ItIsSeven** [comment]
Unfortunately that wouldn't work since it'll always exist on the page as it's a product recommendation that has the "Add to cart" button on the same page as the main thing I want. 
If you have some free time I'd greatly appreciate if you could add this feature if it isn't too difficult to implement. But I can understand if not, and I can also understand if that's outside the scope of this project. 
It would also allow for categories to be monitored rather than individual products, and sites where the "Add to cart" button exists multiple times in a page would be solved with this addition.

Thank you again.

**Comment by hmtessier** [comment]
Changing the alert and keyword parameters as I described above _will_ solve the issue with product recommendations on the same page as you're describing, but if you are looking for additional functionality I recommend using something like distill.io. This script has served its purpose for me and I don't plan on putting any more work into it, although you are welcome to add more features yourself and submit a pull request if you like.
